name: EasyAuth
main: ElementalMinecraftGaming\EasyAuth\Main
version: 1.0.0
api: [3.7.2]
load: POSTWORLD
author: ElementalMinecraftGaming
description: Profile Security!

commands:
 register:
  description: Register!
  permission: easyauth.signup
  aliases: [reg]
 changepw:
  description: change password!
  permission: easyauth.signup
  aliases: [reg]
 changesw:
  description: change safe word!
  permission: easyauth.signup
  aliases: [reg]
 signin:
  description: Sign in!
  permission: easyauth.signin
  aliases: [login]
 safeset:
  description: Register a safe word!
  permission: easyauth.signup
  aliases: [essafe]
 safelogin:
  description: Sign in with safe word!
  permission: easyauth.signin
  aliases: [eslogin]
 logout:
  description: Log out!
  permission: easyauth.signin

permissions:
  easyauth.signup:
    default: true
    description: Let's you register!
  easyauth.signin:
    default: true
    description: Let's you use login!
