name: EasyAuth
main: ElementalMinecraftGaming\EasyAuth\Main
version: 1.0.0
api: [3.7.2]
load: POSTWORLD
author: ElementalMinecraftGaming
description: Profile Security!

commands:
 register:
  description: Register!
  permission: esign.up
  aliases: [reg]
 signin:
  description: Sign in!
  permission: esign.in
  aliases: [login]
 safeset:
  description: Register a safe word!
  permission: esign.up
  aliases: [essafe]
 safelogin:
  description: Sign in with safe word!
  permission: esign.in
  aliases: [eslogin]
 quit:
  description: Leave the server!
  permission: esign.up
 logout:
  description: Log out!
  permission: esign.in

permissions:
  esign.up:
    default: true
    description: Let's you register!
  esign.in:
    default: true
    description: Let's you use login!
